### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by velara3** [GMartigny/crop-node#2]
I'm getting this error when trying to import: 

```
Error [ERR_REQUIRE_ESM]: require() of ES Module project\node_modules\crop-node\index.mjs not supported.
Instead change the require of project\node_modules\crop-node\index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (project\Classes.ts:45:37)
    at m._compile (project\node_modules\ts-node\dist\index.js:857:29)
    at require.extensions.<computed> [as .ts] (project\node_modules\ts-node\dist\index.js:859:16) {
  code: 'ERR_REQUIRE_ESM'
```

When I use:

```js
import crop from "crop-node";
```

or use 

```
const crop = require("crop-node");
```
Example code: 

```ts
export async function trimImage(path, options = null) {
   const crop = require("crop-node");
   const cropped = await crop(path, options);
   return {image: crop, bounds: {x:0,y:0,width:0,height:0}};
}
```

**Comment by GMartigny** [comment]
Hi, it seems that the `type: "module"` was missing. I fixed it and it works for me in Node v20.9.0

Hope this helps

**Comment by velara3** [comment]
Does this change apply if I run `npm update crop-node --dev`?

**Comment by GMartigny** [comment]
It should, check that you have at least v2.1.1 installed with `npm list crop-node`

**Comment by velara3** [comment]
It says 2.1.2. I get the error each time with two lines of code. I add the import and no error: 

```ts
import crop from "crop-tool"
```

As soon as I add the call I get the typescript compile error: 
```ts
var test = await crop(outputPath);;
```
error: 
```
\node_modules\ts-node\dist\index.js:851
        return old(m, filename);
               ^
Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\crop-node\index.js from \MyClass.ts not supported.
Instead change the require of index.js in \MyClass.ts to a dynamic import() which is available in all CommonJS modules.   
at require.extensions.<computed> [as .js] (\node_modules\ts-node\dist\index.js:851:20)
at Object.<anonymous> (\MyClass.ts:49:37)
at m._compile (\node_modules\ts-node\dist\index.js:857:29) {
code: 'ERR_REQUIRE_ES
```

I don't know if it makes a difference but here is my ts-config: 
```
{
	"compilerOptions": {
		"target": "ES6",
		"module": "CommonJS",
		"moduleResolution": "node",
		"allowSyntheticDefaultImports": true,
		"resolveJsonModule": true,
		"pretty": true,
		"sourceMap": true,
		"outDir": "./dist",
		"stripInternal": true,
		"noUncheckedIndexedAccess": true,
		"noPropertyAccessFromIndexSignature": false,
		"noEmitOnError": true,
		"useDefineForClassFields": true,
		"forceConsistentCasingInFileNames": true,
		"skipLibCheck": true,
		"esModuleInterop": true
	}
}
```

**Comment by GMartigny** [comment]
It seems that your TS [is configure to handle CJS](https://www.typescriptlang.org/tsconfig/#module) (Common JS) which `crop-node` is not. Since your target is "ES6", you can just remove the `"module": "CommonJS",` line (or change it to `"module": "ES6",`).

**Comment by velara3** [comment]
Typescript didn't like those changes. I think my project setup has issues. I keep running into errors like these with client side npm packages.

**Comment by velara3** [comment]
I still can't get it to work. 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\crop-node\index.js from \src\Classes.ts not supported.
Instead change the require of index.js in \src\Classes.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by GMartigny** [comment]
Hi,

You shouldn't use `require` to import this module. This is an ESM only build.

I took the time to create [a minimal example](https://stackblitz.com/edit/stackblitz-starters-k4hrbc?file=index.ts,tsconfig.json,package.json) of what you should be doing.

You can run `npm run build` in the console and see that no error is raised.

**Comment by velara3** [comment]
I didn't use require in my project. Your example works I think (I don't know if it is running in the browser) but I couldn't get it to work in my project. Same error as before. I tried to use a dynamic import as the error suggested and same thing. I believe it's probably a typescript error. I tried to use your tsconfig and still had the same thing. I wrote my own for now.
